language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo apt-get -y install pypy
  - sudo apt-get -y install python-sphinx
  - composer selfupdate
  - composer install

script:
  - cd docs
  - make linkcheck
  - cd ..
  - phpunit --coverage-text
